name: SnayPatel
favicon: null
layout_spectrum: 0.9728699764236808
typography_spectrum: 0.9115377038251609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1452768233139068
  lightness: 0.354791457997635
  saturation: 0.761309246532619
  rhythmicContrast: 0.4585294765420258
purpose: []
